// Objective-C API for talking to github.com/ibigbug/SampleGoLib Go package.
//   gobind -lang=objc github.com/ibigbug/SampleGoLib
//
// File is generated by gobind. Do not edit.

#ifndef __SampleGoLib_H__
#define __SampleGoLib_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull SampleGoLibHello(void);

#endif
