
// Objective-C API for talking to the following Go packages
//
//	github.com/ibigbug/SampleGoLib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __SampleGoLib_FRAMEWORK_H__
#define __SampleGoLib_FRAMEWORK_H__

#include "SampleGoLib.objc.h"
#include "Universe.objc.h"

#endif
